'use client';

import { jsPDF } from 'jspdf';

export async function exportToPDF(title, content, language = 'en') {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let fontName = 'helvetica';
    if (language === 'hi') {
      try {
        const { hindiFontBase64 } = await import('@/lib/fonts/hindifont.js');
        doc.addFileToVFS('NotoSansDevanagari.ttf', hindiFontBase64);
        doc.addFont('NotoSansDevanagari.ttf', 'NotoSansDevanagari', 'normal');
        doc.addFont('NotoSansDevanagari.ttf', 'NotoSansDevanagari', 'bold');
        fontName = 'NotoSansDevanagari';
      } catch (err) {
        console.error("Failed to load Hindi font:", err);
        alert("Hindi PDF rendering failed. Please try again.");
        return;
      }
    }

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let y = margin;

    // Header line
    doc.setDrawColor(79, 70, 229); // Premium Indigo
    doc.setLineWidth(0.8);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Title
    doc.setFont(fontName, 'bold');
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); // slate-900
    const titleLines = doc.splitTextToSize(title.toUpperCase(), maxWidth);
    doc.text(titleLines, pageWidth / 2, y, { align: 'center' });
    y += titleLines.length * 10 + 5;

    // Date
    doc.setFont(fontName, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated on ${new Date().toLocaleDateString('en-IN', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    })}`, pageWidth / 2, y, { align: 'center' });
    y += 10;

    // Divider
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.2);
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;

    // Content Settings
    const defaultFontSize = 11;
    const headingFontSize = 14;
    const lineHeight = 7;
    const paragraphSpacing = 4;

    doc.setTextColor(51, 65, 85); // slate-700

    const rawLines = content.split('\n');

    for (let line of rawLines) {
      if (!line.trim()) {
        y += paragraphSpacing;
        continue;
      }

      let isHeading = false;
      let isBullet = false;
      let fontSize = defaultFontSize;
      let fontWeight = 'normal';

      // Detect Headings
      if (line.startsWith('#')) {
        isHeading = true;
        fontWeight = 'bold';
        fontSize = headingFontSize;
        // Clean markdown symbols
        line = line.replace(/^#+\s*/, '');
      } 
      // Detect Bold-only lines
      else if (line.startsWith('**') && line.endsWith('**')) {
        fontWeight = 'bold';
        line = line.replace(/\*\*/g, '');
      }
      // Detect Bullets
      else if (line.startsWith('* ') || line.startsWith('- ')) {
        isBullet = true;
        line = '•  ' + line.substring(2);
      }
      // Detect Numbered Lists
      else if (/^\d+\.\s/.test(line)) {
        // Keep as is
      }

      // Clean remaining ** symbols globally for simplicity in PDF
      const displayText = line.replace(/\*\*/g, '');

      doc.setFont(fontName, fontWeight);
      doc.setFontSize(fontSize);

      if (isHeading) {
        y += 4;
        doc.setTextColor(15, 23, 42); 
      } else {
        doc.setTextColor(51, 65, 85);
      }

      const splitLines = doc.splitTextToSize(displayText, maxWidth);
      
      for (const sl of splitLines) {
        if (y > pageHeight - 25) {
          addFooter(doc, pageWidth, pageHeight, margin);
          doc.addPage();
          y = margin + 10;
        }
        
        doc.text(sl, margin + (isBullet ? 5 : 0), y);
        y += lineHeight;
      }

      if (isHeading) {
        y += 2;
      }
    }

    // Footer on last page
    addFooter(doc, pageWidth, pageHeight, margin);

    // Save
    const fileName = title.replace(/[^a-zA-Z0-9 ]/g, '_').substring(0, 50).trim();
    doc.save(`${fileName}.pdf`);
  } catch (error) {
    console.error("PDF generation error:", error);
    alert("Failed to generate PDF. Please try again.");
  }
}

function addFooter(doc, pageWidth, pageHeight, margin) {
  const pages = doc.internal.getNumberOfPages();
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(
    `Page ${pages} | Securely Generated by LegalDoc AI`,
    pageWidth / 2,
    pageHeight - 12,
    { align: 'center' }
  );
}
